version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8000:8000"

  website:
    build:
      context: .
      dockerfile: Dockerfile.website
    ports:
      - "4000:80"
